### ISSUE TITLE
image overview

### ISSUE THREAD

**Issue by nycex** [eXeC64/imv#243] opened 2020-04-20 18:50 UTC
when opening multiple files with imv, it would be great if you could open a view where you can see them all (maybe not all, set a limit for rows and columns and then scroll or something like that), like you can in sxiv

**Comment by max-k** [comment] 2021-01-19 10:21
I agree with you. A "thumbpane" could be a very nice addition to ease browsing in large pictures folder.

Here is an example of a pane provided by mirage, a gtk/x11 based image viewer.

![image](http://mirageiv.sourceforge.net/images/ss2.png)

**Comment by eXeC64** [comment] 2021-07-08 23:02
Duplicate of #38

**Closed by eXeC64** 2021-07-08 23:02 UTC
