### ISSUE TITLE
Floating pointer exception

### ISSUE THREAD

**Issue by ShanaXXII** [eXeC64/imv#25] opened 2015-11-12 23:00 UTC
Program crashes after window appears for split second.
Had to install FreeImage-3.15.4 and libSDL2-2.0.3-r200 to compile imv.
This is on Gentoo Linux, kernel 4.3.

Installation: 
$ make
COMPILING build/texture.o
COMPILING build/viewport.o
COMPILING build/main.o
COMPILING build/image.o
COMPILING build/navigator.o
LINKING imv
$ sudo make install
install -D -m 0755 imv /usr/bin/imv
install -D -m 0644 doc/imv.1 /usr/share/man/man1/imv.1
install -D -m 0644 files/imv.desktop /usr/share/applications/imv.desktop

Running:
$ imv image.png
Floating point exception

**Comment by jdiez17** [comment] 2015-11-12 23:09
Duplicate of #24.

**Closed by jdiez17** 2015-11-12 23:09 UTC
