### ISSUE TITLE
Command bar is positioned in the middle of the view

### ISSUE THREAD

**Issue by nostdm** [eXeC64/imv#290] opened 2020-11-15 16:40 UTC
Version: v4.1.0-28-g0131ab6
Compositor: sway version 1.5-c523aa62 (Nov  2 2020, branch 'master')
OS: Arch Linux 5.9.8-arch1-1 x86_64 

**Issue:** The command bar that shows up after pressing `:` appears in the middle of the application view as illustrated below. I'm assuming it should be displayed at the bottom of the view by default. I didn't notice any configuration options that can change the position of the bar so it might be a bug.

![image](https://user-images.githubusercontent.com/16334589/99190910-4d78b780-2761-11eb-84c8-0e2a01730f25.png)

**Comment by eXeC64** [comment] 2021-07-08 23:09
Thanks for the report. I'm closing it as a duplicate of #319. Your report came first, I know, but that one has more activity.

**Closed by eXeC64** 2021-07-08 23:09 UTC
