### ISSUE TITLE
Fullscreen doesn't work properly in DWM

### ISSUE THREAD

**Issue by Slider-Whistle** [eXeC64/imv#135] opened 2018-09-19 08:24 UTC
First screenshot shows the image without "when stay_fullscreen_on_focus_loss" set to true (don't mind the scaling factor of 99%, that was caused by me).
Second image enables that setting, but the fact that it's centered offset to the left indicates that the issue's still present.
![1](https://user-images.githubusercontent.com/33862922/45740578-e884ae00-bc38-11e8-9d9d-0042ccc59971.png)
![2](https://user-images.githubusercontent.com/33862922/45740510-c854ef00-bc38-11e8-9388-09dca065a6dd.png)
![3](https://user-images.githubusercontent.com/33862922/45740481-b83d0f80-bc38-11e8-97c9-8a19d5857e4c.png)

Hope you can fix this issue, or at least come up with a good workaround, because this is the one image-viewing program I've found that's any better than feh.

**Comment by Slider-Whistle** [comment] 2018-09-20 09:00
I found a workaround. From what I understand, this may be caused by the wacky behaviour of SDL and as such couldn't be fixed without a total rework of the program, so it's an issue we unfortunately have to work around rather than solve.
In dwm's config.h, I set the "imv" window class as floating, and manually changed imv's window resolution to the size of my monitor (refer to `man 5 imv`). This seems to be what the program would basically try to do anyway, if only it picked a smaller, weaker window manager who couldn't fight back.

**Comment by eXeC64** [comment] 2018-09-20 15:48
This isn't the first bug imv's experienced due to funky SDL behaviour. The main reason SDL was chosen was my previous familiarity with it from gamdev, and its portability (Wayland, etc.). Best case here would be to identify a specific bug in SDL and report it. Alternatively, it may be possible to hack around it using `SDL_GetWindowWMInfo` to access the underlying window and pass some hints in.

I'm not sure I understand the exact issue you're having though. There's 3 screenshots but you only comment on two of them.

**Comment by Slider-Whistle** [comment] 2018-09-21 11:56
Third image is just a version of the second panned over to the right, to demonstrate that the invisible windows on the right appear over it.

**Comment by Slider-Whistle** [comment] 2018-09-21 12:03
Oh, you were unsure what exactly I was making an issue for? It looks like there's two, but I'm pretty sure they're both symptoms of the same thing. Basically, instead of going fullscreen like it's meant to, the window manager keeps it in its own little space. In the third image, the "client windows" are still composited over imv, despite being black, because I guess imv sees that area as being outside of its border, or something.

**Comment by eXeC64** [comment] 2019-06-17 20:04
I expect this will be fixed by the port to glfw as the window/event library for v4.

**Comment by Gigg1ty** [comment] 2019-07-24 13:10
A workaround for users of sway: replace `f = fullscreen` with `f = exec swaymsg -t command fullscreen toggle` in your imv config file.

**Comment by eXeC64** [comment] 2019-08-07 22:58
Most of the window-management work has been merged to master, and will be part of the v4 release. imv now uses wayland/x11 natively, so bugs like this can be addressed properly.

Closing this issue, as it should no longer be reproducible.

**Closed by eXeC64** 2019-08-07 22:58 UTC
Labels: Bug

**Comment by Gigg1ty** [comment] 2019-08-08 04:01
Awesome, thank you so much!
