### ISSUE TITLE
imv unable to open huge images

### ISSUE THREAD

**Issue by Ypnose** [eXeC64/imv#333] opened 2021-05-30 07:46 UTC
Hi,

I tend to save full webpages using the native "Take a Screenshot" option in Firefox. However, `imv-4.2.0` does not display the pictures correctly. When it's opened, the picture stays white and nothing is shown. I'm using `imv` in a Wayland only setup. Firefox displays the picture correctly. Same for `sxiv` in a virtual machine.

Here the picture details :
```
$ file Screenshot_2021-05-30\ lorem\ ipsum\ at\ DuckDuckGo.png
Screenshot_2021-05-30 lorem ipsum at DuckDuckGo.png: PNG image data, 1736 x 32767, 8-bit/color RGBA, non-interlaced
```
```
$ exiftool -all Screenshot_2021-05-30\ lorem\ ipsum\ at\ DuckDuckGo.png 
ExifTool Version Number         : 12.26
File Name                       : Screenshot_2021-05-30 lorem ipsum at DuckDuckGo.png
Directory                       : .
File Size                       : 4.6 MiB
File Modification Date/Time     : 2021:05:30 09:33:45+02:00
File Access Date/Time           : 2021:05:30 09:33:45+02:00
File Inode Change Date/Time     : 2021:05:30 09:33:45+02:00
File Permissions                : -rw-------
File Type                       : PNG
File Type Extension             : png
MIME Type                       : image/png
Image Width                     : 1736
Image Height                    : 32767
Bit Depth                       : 8
Color Type                      : RGB with Alpha
Compression                     : Deflate/Inflate
Filter                          : Adaptive
Interlace                       : Noninterlaced
Image Size                      : 1736x32767
Megapixels                      : 56.9
```
The example picture can be downloaded [here](https://ufile.io/0in5z101) (will be removed in one month).

**Comment by eXeC64** [comment] 2021-07-08 22:22
Thanks for the report. This is a duplicate of #327, imv needs to start breaking up images into multiple OpenGL textures to handle very large images.

Closing as a duplicate.

**Closed by eXeC64** 2021-07-08 22:22 UTC
