### ISSUE TITLE
core dumps on failing assertion

### ISSUE THREAD

**Issue by HalosGhost** [eXeC64/imv#163] opened 2019-08-08 01:21 UTC
## System

Distro: Archlinux
package: -git built from master

## Additional Information

wayland 1.17.0-1 installed (but not being used)
This issue happens for me, at least, under dwm 6.2

## Problem

When running `imv` under a lightweight Xlib-based window manager (i.e., without wayland running), it crashes on a failed assertion.

Output of run:

```console
% imv ./arch-base.svg
imv: src/wl_window.c:578: connect_to_wayland: Assertion `window->wl_display' failed.
zsh: abort (core dumped)  imv -b checks ./arch-base.svg
```

Full stack trace:

```
Stack trace of thread 20740:
#0  0x00007f1ad9acd755 raise (libc.so.6)
#1  0x00007f1ad9ab8851 abort (libc.so.6)
#2  0x00007f1ad9ab8727 __assert_fail_base.cold (libc.so.6)
#3  0x00007f1ad9ac6026 __assert_fail (libc.so.6)
#4  0x0000556d6e92ee45 n/a (imv)
#5  0x0000556d6e92bc6d n/a (imv)
#6  0x0000556d6e927bea n/a (imv)
#7  0x00007f1ad9ab9ee3 __libc_start_main (libc.so.6)
#8  0x0000556d6e927c3e n/a (imv)

Stack trace of thread 20741:
#0  0x00007f1ada901b9f accept (libpthread.so.0)
#1  0x0000556d6e92cd8e n/a (imv)
#2  0x00007f1ada8f857f start_thread (libpthread.so.0)
#3  0x00007f1ad9b8f0e3 __clone (libc.so.6)
```

## Steps to Reproduce

1. Be using a non-wayland-based window manager
1. Run `imv` on any image file (tested both with the new SVG functionality and a PNG)
1. Notice that, rather than the image opening, `imv` crashes

**Comment by eXeC64** [comment] 2019-08-08 08:05
Ah. In the current state of master, imv now uses Wayland/X11 directly. The windowing system is selected at build time, with Wayland being the default. If you add a step along the lines of `sed -i config.mk 's/WINDOWS=wayland/WINDOWS=x11/` to the `PKGBUILD`, you should see it working normally with X11.

My expectation is that in future two alternative packages would be provided, like `glfw-wayland` and `glfw-x11` on Arch, which both provide the `glfw` meta-package.

**Comment by HalosGhost** [comment] 2019-08-08 14:40
Interesting. Is it not possible to provide this as either a configuration option? I will try to build it tonight to verify that it works for me with x11.

**Comment by eXeC64** [comment] 2019-08-08 19:19
It's possible to make changes to build against both, but that introduces a dependency on both X11 and Wayland when I'd prefer imv to just use whatever's available. That's unless I use dynamic linking to pull in the required symbols manually, but I'm not fond of that either.

**Comment by HalosGhost** [comment] 2019-08-08 20:33
It could be an optional dependency on both, no? And then, if you don't have one installed and attempt to use it, it'd fail. Would that not work?

**Comment by eXeC64** [comment] 2019-08-08 21:18
Perhaps my knowledge of dynamic linking is too limited, but how I understand it is: If I build imv and link against both wayland-client and X11, if either of these is not installed, then the dynamic linker will fail to load the required shared object, and imv will not start.

If there's a portable way to support this other than explicitly calling `dlsym` for everything required from `wayland-client`, `wayland-egl`, `EGL`, `X11`, `GL`, and `GLU` I'd be glad to hear it.

**Comment by rien333** [comment] 2019-08-11 14:29
Because HalosGhost did not reply yet: I can confirm that adding `sed -i 's/WINDOWS=wayland/WINDOWS=x11/' config.mk` (note the reverse arguments!) to the `PKGBUILD` works.

**Comment by eXeC64** [comment] 2019-08-11 23:42
Okay, I came up with a third option which looks like this:

- Build both Wayland and X11 versions as separate binaries, `imv-wl` and `imv-x11`
- Ship 'em both
- Also ship a shell script as `/usr/bin/imv` which checks for a wayland compositor (is `$WAYLAND_DISPLAY` set?), and runs the appropriate build.

This is now the default option on master, but you can also select `x11` or `wayland` explicitly and have your preferred version installed as `/usr/bin/imv` directly. I think this provides a nice middle ground of just working for people who don't care, and being easily configurable for people who want to keep their system as pure X11 or pure Wayland.

This should resolve this issue, so I'm going to go ahead and close it. Feel free to open a new issue with any problems.

**Closed by eXeC64** 2019-08-11 23:42 UTC
